### ISSUE TITLE
Your project music-web has been banned by WeChat

### ISSUE THREAD

**Issue by MiddleHand** [Yamabuki-bakery/music-web#1]
Hello , I recently found out that your website MyPass has been banned by WeChat and I could not find a new one on GitHub . Wondering if you could build a new one at your convenience . Thank you very much for your time.

**Comment by Yamabuki-bakery** [comment]
Hello, thanks for reminding, but you fork this Repo and deploy to Cloudflare Pages by your own,
it is the most convenient way to create a new website.

**Comment by ShevonKuan** [comment]
Use ksweb pro to deploy it on your phone locally. This  should be the safetest way.

**Comment by MiddleHand** [comment]
> Hello, thanks for reminding, but you can fork this Repo and deploy to Cloudflare Pages by your own, it is the most convenient way to create a new website.

I tried to upload the folder DOOR in [music-web]/source/ to Cloudflare Pages and it failed ( now error 404 , first 522,523 ). 
And I also tried uploading the template provided by the official and it works correctly . So do you have any idea that which steps may caused the problem or maybe there are more steps I did not follow .

**Comment by MiddleHand** [comment]
> Use ksweb pro to deploy it on your phone locally. This should be the safetest way.

Thank you very much for your suggestion . Can you tell me the repository you used ?
